---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        run: my-nginx
        version: 2.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32111"
    spec:
      containers:
      - name: my-nginx
        image: signorini/nginx-openrest:app2

        ports:
        - containerPort: 80
        - containerPort: 32111
